ZSH=$HOME/.oh-my-zsh
export PATH="./bin:/usr/local/bin:/usr/local/sbin:$ZSHDOT/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export PATH=/usr/local/bin:$PATH
export PATH=~/bin:$PATH
export NODE_PATH=$NODE_PATH:/usr/lib/node_modules/
#export PATH=/usr/local/php5/bin:$PATH 
export AWS_RDS_HOME=~/bin/RDSCli
export PGHOST=localhost
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
